# Generated by Django 4.2.27 on 2026-01-03 08:29

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOffType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('PAID', 'Paid Time Off'), ('SICK', 'Sick Leave'), ('UNPAID', 'Unpaid Leave')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('default_annual_allocation_days', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Time Off Type',
                'verbose_name_plural': 'Time Off Types',
                'db_table': 'timeoff_types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('allocation_days', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))])),
                ('attachment', models.FileField(blank=True, null=True, upload_to='timeoff_attachments/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeoff_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeoff_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeoff_requests_created', to=settings.AUTH_USER_MODEL)),
                ('timeoff_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='timeoff.timeofftype')),
            ],
            options={
                'verbose_name': 'Time Off Request',
                'verbose_name_plural': 'Time Off Requests',
                'db_table': 'timeoff_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='timeoff_req_employe_0e04fc_idx'), models.Index(fields=['status', 'created_at'], name='timeoff_req_status_b816b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeOffBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('allocated_days', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('used_days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timeoff_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='timeoff.timeofftype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeoff_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Off Balance',
                'verbose_name_plural': 'Time Off Balances',
                'db_table': 'timeoff_balances',
                'ordering': ['-year', 'timeoff_type__code'],
                'unique_together': {('user', 'timeoff_type', 'year')},
            },
        ),
    ]
